#!/usr/bin/env python3
"""Generate reference indicator values from pandas-ta for cross-validation.

Outputs a Go-embeddable struct with pre-computed values.
Uses a deterministic OHLCV series (seeded PRNG) so results are reproducible.
"""

import json
import math
import numpy as np
import pandas as pd
import pandas_ta as ta

np.random.seed(42)

N = 60  # 60 bars — enough for all indicators to warm up

# Generate realistic OHLCV: random walk with drift
closes = [100.0]
for i in range(1, N):
    closes.append(closes[-1] + np.random.normal(0.3, 1.5))
closes = np.array(closes)

highs = closes + np.abs(np.random.normal(1.0, 0.5, N))
lows = closes - np.abs(np.random.normal(1.0, 0.5, N))
opens = (closes + np.random.normal(0, 0.3, N))
volumes = np.abs(np.random.normal(1000, 200, N))

df = pd.DataFrame({
    "open": opens,
    "high": highs,
    "low": lows,
    "close": closes,
    "volume": volumes,
})

# Compute indicators using pandas-ta
rsi = ta.rsi(df["close"], length=14)
stoch = ta.stoch(df["high"], df["low"], df["close"], k=14, d=3, smooth_k=1)
ema9 = ta.ema(df["close"], length=9)
ema21 = ta.ema(df["close"], length=21)
ema50 = ta.ema(df["close"], length=50)
bb = ta.bbands(df["close"], length=20, std=2.0)
macd = ta.macd(df["close"], fast=12, slow=26, signal=9)
adx_df = ta.adx(df["high"], df["low"], df["close"], length=14)

# VWAP: cumulative (treating all bars as one session)
typical = (df["high"] + df["low"] + df["close"]) / 3
cum_tp_vol = (typical * df["volume"]).cumsum()
cum_vol = df["volume"].cumsum()
vwap = cum_tp_vol / cum_vol

# ATR
atr = ta.atr(df["high"], df["low"], df["close"], length=14)

# Print OHLCV data as Go slice literals
print("// AUTO-GENERATED by generate_reference.py — do not edit")
print("// pandas-ta version, seed=42, N=60")
print()

def fmt_slice(name, arr):
    vals = ", ".join(f"{v:.6f}" for v in arr)
    print(f"var {name} = []float64{{{vals}}}")

fmt_slice("refOpen", opens)
fmt_slice("refHigh", highs)
fmt_slice("refLow", lows)
fmt_slice("refClose", closes)
fmt_slice("refVolume", volumes)
print()

# We'll check the last bar (index 59)
i = N - 1
print(f"// Reference values at bar index {i}:")

def safe(series, idx):
    v = series.iloc[idx]
    if pd.isna(v):
        return 0.0
    return float(v)

print(f"const refRSI = {safe(rsi, i):.6f}")
print(f"const refStochK = {safe(stoch.iloc[:, 0], i):.6f}")  # STOCHk_14_3_1
print(f"const refStochD = {safe(stoch.iloc[:, 1], i):.6f}")  # STOCHd_14_3_1
print(f"const refEMA9 = {safe(ema9, i):.6f}")
print(f"const refEMA21 = {safe(ema21, i):.6f}")
print(f"const refEMA50 = {safe(ema50, i):.6f}")
print(f"const refBBUpper = {safe(bb.iloc[:, 2], i):.6f}")   # BBU
print(f"const refBBMiddle = {safe(bb.iloc[:, 1], i):.6f}")  # BBM
print(f"const refBBLower = {safe(bb.iloc[:, 0], i):.6f}")   # BBL
print(f"const refBBPercentB = {safe(bb.iloc[:, 4], i):.6f}")  # BBP (%B)
print(f"const refBBBandwidth = {safe(bb.iloc[:, 3], i):.6f}")  # BBB
print(f"const refMACDLine = {safe(macd.iloc[:, 0], i):.6f}")
print(f"const refMACDSignal = {safe(macd.iloc[:, 2], i):.6f}")
print(f"const refMACDHistogram = {safe(macd.iloc[:, 1], i):.6f}")
print(f"const refADX = {safe(adx_df.iloc[:, 0], i):.6f}")  # ADX_14
print(f"const refATR = {safe(atr, i):.6f}")
print(f"const refVWAP = {safe(vwap, i):.6f}")

# Also print the BB column names for verification
print()
print(f"// BB columns: {list(bb.columns)}")
print(f"// MACD columns: {list(macd.columns)}")
print(f"// ADX columns: {list(adx_df.columns)}")
print(f"// Stoch columns: {list(stoch.columns)}")
