package monitor_test

// Cross-validation of indicator calculations against pandas-ta reference values.
// Reference generated by testdata/generate_reference.py (seed=42, N=60).

import (
	"testing"
	"time"

	"github.com/oh-my-opentrade/backend/internal/app/monitor"
	"github.com/oh-my-opentrade/backend/internal/domain"
	"github.com/stretchr/testify/assert"
)

// ---------------------------------------------------------------------------
// Reference OHLCV data (deterministic, seed=42, 60 bars)
// ---------------------------------------------------------------------------

var refOpen = []float64{100.816051, 101.232771, 100.880528, 102.087940, 105.138494, 104.875483, 105.105517, 107.702107, 108.989440, 108.353038, 109.266463, 109.191836, 109.184115, 109.654367, 106.646497, 104.784796, 104.305006, 102.705007, 103.787652, 102.696961, 100.518152, 103.466853, 103.489087, 104.047060, 102.201163, 100.955147, 101.553484, 100.562852, 101.426024, 100.825445, 101.689209, 100.102097, 103.349917, 103.575202, 102.197852, 103.441671, 102.232677, 102.386435, 99.907731, 98.140889, 98.906352, 100.983887, 100.286362, 101.178948, 100.337599, 98.762051, 98.450550, 97.752191, 99.295266, 100.219426, 98.293336, 98.656473, 98.662897, 97.896248, 98.904611, 101.589774, 102.833686, 101.077141, 101.576802, 102.119225}
var refHigh = []float64{101.487773, 101.805484, 102.044845, 102.856040, 105.395649, 106.348785, 106.569437, 108.524131, 110.513055, 109.787895, 110.398357, 110.506488, 110.696214, 110.572226, 108.802540, 105.042714, 105.600362, 104.013687, 104.592031, 103.725379, 100.867259, 104.249680, 104.499408, 105.461091, 102.625887, 101.964201, 102.583953, 101.866042, 102.436264, 101.406050, 101.790023, 100.979369, 104.493570, 103.937975, 102.838604, 104.340198, 102.273229, 103.766342, 101.109305, 99.289055, 99.764496, 100.581804, 101.636219, 101.801712, 101.420275, 99.822988, 99.325890, 99.676000, 100.705879, 101.562793, 99.052234, 98.916197, 99.584703, 98.912692, 101.331712, 101.850410, 103.794284, 102.667328, 101.936527, 103.889172}
var refLow = []float64{98.624033, 99.649555, 100.592369, 100.707810, 104.694678, 103.649094, 102.796089, 107.055404, 108.294437, 107.557251, 108.972655, 109.101122, 107.892914, 109.121291, 105.783422, 104.192554, 102.414443, 102.361790, 102.902566, 101.272740, 100.476475, 102.245786, 101.667280, 103.525886, 100.792705, 100.238506, 100.443920, 100.026817, 100.932117, 99.409960, 99.384897, 98.805583, 101.836023, 102.629014, 100.886308, 102.389716, 101.362162, 100.685395, 98.741860, 97.882150, 97.553513, 99.776830, 99.453000, 99.393772, 100.231755, 97.421943, 96.917474, 96.321876, 97.670193, 99.556711, 97.466325, 98.320340, 98.005865, 96.921127, 97.929515, 99.808245, 101.229919, 100.678183, 99.794099, 101.450089}
var refClose = []float64{100.000000, 101.045071, 101.137675, 102.409208, 104.993752, 104.942522, 104.891317, 107.560136, 109.011288, 108.607077, 109.720917, 109.325790, 108.927196, 109.590139, 107.020219, 104.732842, 104.189411, 102.970164, 103.741535, 102.679499, 100.861043, 103.359516, 103.320852, 103.722144, 101.885022, 101.368448, 101.834832, 100.408341, 101.271888, 100.670930, 100.533390, 99.930830, 103.009247, 103.289001, 102.002435, 103.536252, 102.004987, 102.618282, 99.978777, 98.286498, 98.881790, 100.289490, 100.846542, 100.973070, 100.821414, 98.903631, 98.123865, 97.732907, 99.618590, 100.434017, 98.089457, 98.875583, 98.597960, 97.882577, 99.100091, 100.946590, 102.643511, 101.684684, 101.520866, 102.317761}
var refVolume = []float64{1170.486667, 841.495852, 977.052712, 1100.997456, 1173.151039, 759.940719, 933.099753, 905.010938, 869.334153, 1353.090848, 1080.996342, 747.823209, 1183.572389, 1424.431239, 1206.493052, 696.126007, 903.153185, 1253.382230, 858.466107, 1088.763886, 1154.926811, 814.613906, 988.094929, 351.746532, 795.122472, 949.486370, 750.443364, 1326.482261, 713.971724, 911.991103, 1026.148115, 1288.254658, 712.827570, 1232.632750, 1002.046612, 803.698270, 1092.420695, 1039.811939, 879.956625, 1013.960417, 922.937281, 1022.703469, 1132.426135, 1317.203363, 752.436900, 1426.606675, 609.582440, 969.642981, 1117.663441, 1056.198374, 875.460096, 958.375550, 901.399813, 882.127049, 1169.920419, 1071.403097, 861.418081, 1179.919975, 1061.459904, 1162.572424}

// pandas-ta reference values at bar 59
const (
	refRSI           = 56.785784
	refStochK        = 79.234175
	refStochD        = 73.526045
	refEMA9          = 100.920086
	refEMA21         = 100.565318
	refEMA50         = 101.962876
	refBBUpper       = 102.968178
	refBBMiddle      = 99.914220
	refBBLower       = 96.860262
	refBBPercentB    = 0.893512
	refBBBandwidthPT = 6.113160 // pandas-ta uses percentage (×100)
	refMACDLine      = -0.017946
	refMACDSignal    = -0.547861
	refMACDHistogram = 0.529915
	refADX           = 11.767631
	refATR           = 2.400472
	refVWAP          = 102.351946
)

var crossValBaseTime = time.Date(2026, 1, 5, 9, 30, 0, 0, time.UTC)

func feedRefBars(t *testing.T, calc *monitor.IndicatorCalculator, sym domain.Symbol) domain.IndicatorSnapshot {
	t.Helper()
	var snap domain.IndicatorSnapshot
	for i := 0; i < len(refClose); i++ {
		bar, err := domain.NewMarketBar(
			crossValBaseTime.Add(time.Duration(i)*time.Minute),
			sym, "1m",
			refOpen[i], refHigh[i], refLow[i], refClose[i],
			refVolume[i],
		)
		if err != nil {
			t.Fatalf("bar %d: %v", i, err)
		}
		snap = calc.Update(bar)
	}
	return snap
}

// ---------------------------------------------------------------------------
// Cross-validation tests
// ---------------------------------------------------------------------------

func TestCrossVal_RSI(t *testing.T) {
	calc := monitor.NewIndicatorCalculator()
	sym, _ := domain.NewSymbol("AAPL")
	snap := feedRefBars(t, calc, sym)

	// pandas-ta RSI uses Wilder's smoothing (EMA); ours uses simple window average.
	// These diverge, so we accept a wider tolerance for RSI.
	assert.InDelta(t, refRSI, snap.RSI, 8.0,
		"RSI: ours=%.2f, pandas-ta=%.2f (SMA vs Wilder method — wider tolerance expected)", snap.RSI, refRSI)
}

func TestCrossVal_Stochastic(t *testing.T) {
	calc := monitor.NewIndicatorCalculator()
	sym, _ := domain.NewSymbol("AAPL")
	snap := feedRefBars(t, calc, sym)

	assert.InDelta(t, refStochK, snap.StochK, 1.0,
		"StochK: ours=%.2f, pandas-ta=%.2f", snap.StochK, refStochK)
	assert.InDelta(t, refStochD, snap.StochD, 3.0,
		"StochD: ours=%.2f, pandas-ta=%.2f", snap.StochD, refStochD)
}

func TestCrossVal_EMA(t *testing.T) {
	calc := monitor.NewIndicatorCalculator()
	sym, _ := domain.NewSymbol("AAPL")
	snap := feedRefBars(t, calc, sym)

	assert.InDelta(t, refEMA9, snap.EMA9, 0.05,
		"EMA9: ours=%.6f, pandas-ta=%.6f", snap.EMA9, refEMA9)
	assert.InDelta(t, refEMA21, snap.EMA21, 0.05,
		"EMA21: ours=%.6f, pandas-ta=%.6f", snap.EMA21, refEMA21)
	assert.InDelta(t, refEMA50, snap.EMA50, 0.05,
		"EMA50: ours=%.6f, pandas-ta=%.6f", snap.EMA50, refEMA50)
}

func TestCrossVal_BollingerBands(t *testing.T) {
	calc := monitor.NewIndicatorCalculator()
	sym, _ := domain.NewSymbol("AAPL")
	snap := feedRefBars(t, calc, sym)

	assert.InDelta(t, refBBMiddle, snap.BBMiddle, 0.05,
		"BB Middle: ours=%.6f, pandas-ta=%.6f", snap.BBMiddle, refBBMiddle)
	assert.InDelta(t, refBBUpper, snap.BBUpper, 0.01,
		"BB Upper: ours=%.6f, pandas-ta=%.6f", snap.BBUpper, refBBUpper)
	assert.InDelta(t, refBBLower, snap.BBLower, 0.01,
		"BB Lower: ours=%.6f, pandas-ta=%.6f", snap.BBLower, refBBLower)
	assert.InDelta(t, refBBPercentB, snap.BBPercentB, 0.005,
		"BB %%B: ours=%.6f, pandas-ta=%.6f", snap.BBPercentB, refBBPercentB)
	// pandas-ta bandwidth is ×100 (percentage), ours is ratio
	assert.InDelta(t, refBBBandwidthPT/100.0, snap.BBBandwidth, 0.0005,
		"BB Bandwidth: ours=%.6f, pandas-ta=%.6f (÷100)", snap.BBBandwidth, refBBBandwidthPT/100.0)
}

func TestCrossVal_MACD(t *testing.T) {
	calc := monitor.NewIndicatorCalculator()
	sym, _ := domain.NewSymbol("AAPL")
	snap := feedRefBars(t, calc, sym)

	// MACD line should match closely — same EMA formula
	assert.InDelta(t, refMACDLine, snap.MACDLine, 0.15,
		"MACD Line: ours=%.6f, pandas-ta=%.6f", snap.MACDLine, refMACDLine)
	// Signal line may differ due to seeding approach
	assert.InDelta(t, refMACDSignal, snap.MACDSignal, 0.5,
		"MACD Signal: ours=%.6f, pandas-ta=%.6f (seeding tolerance)", snap.MACDSignal, refMACDSignal)
	// Histogram = Line - Signal — propagates both errors
	assert.InDelta(t, refMACDHistogram, snap.MACDHistogram, 0.6,
		"MACD Histogram: ours=%.6f, pandas-ta=%.6f", snap.MACDHistogram, refMACDHistogram)
}

func TestCrossVal_ATR(t *testing.T) {
	calc := monitor.NewIndicatorCalculator()
	sym, _ := domain.NewSymbol("AAPL")
	snap := feedRefBars(t, calc, sym)

	assert.InDelta(t, refATR, snap.ATR, 0.15,
		"ATR: ours=%.6f, pandas-ta=%.6f", snap.ATR, refATR)
}

func TestCrossVal_VWAP(t *testing.T) {
	calc := monitor.NewIndicatorCalculator()
	sym, _ := domain.NewSymbol("AAPL")
	snap := feedRefBars(t, calc, sym)

	assert.InDelta(t, refVWAP, snap.VWAP, 0.01,
		"VWAP: ours=%.6f, pandas-ta=%.6f", snap.VWAP, refVWAP)
}

func TestCrossVal_ADX(t *testing.T) {
	calc := monitor.NewIndicatorCalculator()
	sym, _ := domain.NewSymbol("AAPL")
	snap := feedRefBars(t, calc, sym)

	// ADX implementations vary significantly due to initialization/smoothing differences.
	// We verify directional agreement (both indicate weak trend) rather than exact match.
	assert.InDelta(t, refADX, snap.ADX, 15.0,
		"ADX: ours=%.2f, pandas-ta=%.2f (wide tolerance — initialization differs)", snap.ADX, refADX)
	// Both should agree this is a weak/no trend (< 30)
	assert.Less(t, snap.ADX, 40.0, "ADX should indicate weak trend for this choppy data")
}
