ALTER TABLE trades
  ADD COLUMN IF NOT EXISTS instrument_type TEXT DEFAULT 'EQUITY',
  ADD COLUMN IF NOT EXISTS option_symbol TEXT,
  ADD COLUMN IF NOT EXISTS underlying TEXT,
  ADD COLUMN IF NOT EXISTS strike DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS expiry TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS option_right TEXT,
  ADD COLUMN IF NOT EXISTS premium DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS delta_at_entry DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS iv_at_entry DOUBLE PRECISION;

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS instrument_type TEXT DEFAULT 'EQUITY',
  ADD COLUMN IF NOT EXISTS option_symbol TEXT,
  ADD COLUMN IF NOT EXISTS underlying TEXT,
  ADD COLUMN IF NOT EXISTS strike DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS expiry TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS option_right TEXT;
