[SERVICE]
    Flush        1
    Log_Level    info
    Daemon       off
    HTTP_Server  Off

[INPUT]
    Name         tail
    Path         /var/log/omo-core/omo-core.log
    Tag          omo
    Read_from_Head true
    Refresh_Interval 5

[OUTPUT]
    Name         loki
    Match        *
    Host         loki
    Port         3100
    Labels       job=omo-core
    Auto_Kubernetes_Labels off
