package strategy

import (
	"fmt"
	"time"
)

// CandidateAnchorType classifies the origin of a candidate anchor point.
type CandidateAnchorType string

const (
	AnchorSwingHigh      CandidateAnchorType = "swing_high"
	AnchorSwingLow       CandidateAnchorType = "swing_low"
	AnchorVolumeRotation CandidateAnchorType = "volume_rotation"
	AnchorWeeklyOpen     CandidateAnchorType = "weekly_open"
	AnchorSessionDerived CandidateAnchorType = "session_derived"
)

// ValidAnchorTypes is the set of valid CandidateAnchorType values.
var ValidAnchorTypes = map[CandidateAnchorType]bool{
	AnchorSwingHigh:      true,
	AnchorSwingLow:       true,
	AnchorVolumeRotation: true,
	AnchorWeeklyOpen:     true,
	AnchorSessionDerived: true,
}

// VolumeRotationContext holds metadata about a detected volume rotation zone.
// Populated only for AnchorVolumeRotation candidates.
type VolumeRotationContext struct {
	RotationBars   int        // number of bars in the rotation zone
	AvgVolume      float64    // average volume during the rotation
	BreakoutVolume float64    // volume of the breakout bar
	PriceRange     [2]float64 // [low, high] of the rotation zone
}

// CandidateAnchor represents a potential VWAP anchor point detected by
// deterministic algorithms. Candidates are generated by SwingDetector,
// VolumeProfiler, or WeeklyAnchorDetector and later ranked by the LLM
// or a deterministic fallback scorer.
type CandidateAnchor struct {
	ID            string              // unique identifier: "{type}_{timeframe}_{unix_ts}"
	Time          time.Time           // when the anchor event occurred
	Price         float64             // price level at the anchor point
	Type          CandidateAnchorType // classification of anchor origin
	Timeframe     string              // bar timeframe where detected (e.g. "5m", "1h", "1d")
	Strength      float64             // detection confidence (higher = more confirmations)
	VolumeContext *VolumeRotationContext
	Source        string // "algo", "session", "manual"
	TouchCount    int    // how many times price has respected this level since formation
}

// NewCandidateAnchor creates a validated CandidateAnchor with an auto-generated ID.
func NewCandidateAnchor(t time.Time, price float64, anchorType CandidateAnchorType, timeframe string, strength float64) (CandidateAnchor, error) {
	if t.IsZero() {
		return CandidateAnchor{}, fmt.Errorf("candidate anchor: time must not be zero")
	}
	if price <= 0 {
		return CandidateAnchor{}, fmt.Errorf("candidate anchor: price must be positive, got %f", price)
	}
	if !ValidAnchorTypes[anchorType] {
		return CandidateAnchor{}, fmt.Errorf("candidate anchor: invalid type %q", anchorType)
	}
	if timeframe == "" {
		return CandidateAnchor{}, fmt.Errorf("candidate anchor: timeframe must not be empty")
	}
	if strength < 0 {
		return CandidateAnchor{}, fmt.Errorf("candidate anchor: strength must be non-negative, got %f", strength)
	}

	id := fmt.Sprintf("%s_%s_%d", anchorType, timeframe, t.Unix())
	return CandidateAnchor{
		ID:        id,
		Time:      t,
		Price:     price,
		Type:      anchorType,
		Timeframe: timeframe,
		Strength:  strength,
		Source:    "algo",
	}, nil
}

// AnchorName returns a stable key suitable for use with AnchoredVWAPCalc.AddAnchor().
// Format: "{type}_{timeframe}_{unix_ts}" (same as ID).
func (c CandidateAnchor) AnchorName() string {
	return c.ID
}

// IsSwing returns true if the candidate is a swing high or swing low.
func (c CandidateAnchor) IsSwing() bool {
	return c.Type == AnchorSwingHigh || c.Type == AnchorSwingLow
}

// WithVolumeContext returns a copy of the candidate with volume rotation metadata attached.
func (c CandidateAnchor) WithVolumeContext(ctx VolumeRotationContext) CandidateAnchor {
	c.VolumeContext = &ctx
	return c
}

// WithTouchCount returns a copy of the candidate with the touch count set.
func (c CandidateAnchor) WithTouchCount(count int) CandidateAnchor {
	c.TouchCount = count
	return c
}
